name: Making a Bastion Host CDK Synth

on:
  push:
    branches:
      - master
jobs:
  synth:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        working-directory: src/making-a-bastion-host
        run: npm install
      - name: cdk synth
        working-directory: ./src/making-a-bastion-host
        run: npm run synth
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_ACCOUNT_NUMBER: ${{ secrets.AWS_ACCOUNT_NUMBER }}
